// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for www.mml.com
package test

import (
	"encoding/xml"
)

// Element
type Piecewise struct {
	XMLName xml.Name `xml:"piecewise"`
	Id      string   `xml:"id,attr"`
}

// Element
type Apply struct {
	XMLName   xml.Name   `xml:"apply"`
	Piecewise *Piecewise `xml:",any"`
}

// XSD ComplexType declarations

// XSD SimpleType declarations
